// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ast_schema.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scenario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Setup         *Pipeline              `protobuf:"bytes,2,opt,name=setup,proto3" json:"setup,omitempty"`
	Execution     *Pipeline              `protobuf:"bytes,3,opt,name=execution,proto3" json:"execution,omitempty"`
	Config        *ScenarioConfig        `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Teardown      *Pipeline              `protobuf:"bytes,5,opt,name=teardown,proto3" json:"teardown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_ast_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Scenario) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scenario) GetSetup() *Pipeline {
	if x != nil {
		return x.Setup
	}
	return nil
}

func (x *Scenario) GetExecution() *Pipeline {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *Scenario) GetConfig() *ScenarioConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Scenario) GetTeardown() *Pipeline {
	if x != nil {
		return x.Teardown
	}
	return nil
}

type ScenarioConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of concurrent virtual users. Defaults to 1.
	Vus *int32 `protobuf:"varint,1,opt,name=vus,proto3,oneof" json:"vus,omitempty"`
	// Scenario run duration. Stops when reached.
	Duration *string `protobuf:"bytes,2,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	// Hard upper limit for the entire scenario.
	MaxDuration *string `protobuf:"bytes,3,opt,name=max_duration,json=maxDuration,proto3,oneof" json:"max_duration,omitempty"`
	// Number of iterations to execute. Defaults to 1.
	Iterations *int32 `protobuf:"varint,4,opt,name=iterations,proto3,oneof" json:"iterations,omitempty"`
	// Exact time to start the scenario. Takes precedence over order.
	StartAt *string `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3,oneof" json:"start_at,omitempty"`
	// Execution order. Scenarios with the same order start together.
	Order *int32 `protobuf:"varint,6,opt,name=order,proto3,oneof" json:"order,omitempty"`
	// Optional load stages for gradually changing VUs.
	Stages []*Stage `protobuf:"bytes,7,rep,name=stages,proto3" json:"stages,omitempty"`
	// Pass/fail conditions for scenario metrics.
	Thresholds map[string]string `protobuf:"bytes,8,rep,name=thresholds,proto3" json:"thresholds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Custom metadata attached to the scenario.
	Tags map[string]string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Disable TLS certificate verification.
	InsecureSkipTlsVerify *bool `protobuf:"varint,10,opt,name=insecure_skip_tls_verify,json=insecureSkipTlsVerify,proto3,oneof" json:"insecure_skip_tls_verify,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ScenarioConfig) Reset() {
	*x = ScenarioConfig{}
	mi := &file_ast_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioConfig) ProtoMessage() {}

func (x *ScenarioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioConfig.ProtoReflect.Descriptor instead.
func (*ScenarioConfig) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{1}
}

func (x *ScenarioConfig) GetVus() int32 {
	if x != nil && x.Vus != nil {
		return *x.Vus
	}
	return 0
}

func (x *ScenarioConfig) GetDuration() string {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return ""
}

func (x *ScenarioConfig) GetMaxDuration() string {
	if x != nil && x.MaxDuration != nil {
		return *x.MaxDuration
	}
	return ""
}

func (x *ScenarioConfig) GetIterations() int32 {
	if x != nil && x.Iterations != nil {
		return *x.Iterations
	}
	return 0
}

func (x *ScenarioConfig) GetStartAt() string {
	if x != nil && x.StartAt != nil {
		return *x.StartAt
	}
	return ""
}

func (x *ScenarioConfig) GetOrder() int32 {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return 0
}

func (x *ScenarioConfig) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *ScenarioConfig) GetThresholds() map[string]string {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

func (x *ScenarioConfig) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ScenarioConfig) GetInsecureSkipTlsVerify() bool {
	if x != nil && x.InsecureSkipTlsVerify != nil {
		return *x.InsecureSkipTlsVerify
	}
	return false
}

type Stage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Duration of this stage.
	Duration string `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	// Target number of virtual users.
	Target        int32 `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_ast_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Stage) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Stage) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

type Pipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*Node                `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_ast_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{3}
}

func (x *Pipeline) GetSteps() []*Node {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*Node_Action
	//	*Node_Branch
	//	*Node_Match
	//	*Node_Loop
	//	*Node_Poll
	//	*Node_Script
	//	*Node_Sleep
	//	*Node_Log
	//	*Node_Barrier
	//	*Node_Set
	//	*Node_Distribute
	//	*Node_Metric
	//	*Node_ReqMutate
	//	*Node_ResAssert
	//	*Node_Tag
	Type          isNode_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_ast_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{4}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetType() isNode_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Node) GetAction() *ActionNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Action); ok {
			return x.Action
		}
	}
	return nil
}

func (x *Node) GetBranch() *BranchNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Branch); ok {
			return x.Branch
		}
	}
	return nil
}

func (x *Node) GetMatch() *MatchNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Match); ok {
			return x.Match
		}
	}
	return nil
}

func (x *Node) GetLoop() *LoopNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Loop); ok {
			return x.Loop
		}
	}
	return nil
}

func (x *Node) GetPoll() *PollNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Poll); ok {
			return x.Poll
		}
	}
	return nil
}

func (x *Node) GetScript() *ScriptNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Script); ok {
			return x.Script
		}
	}
	return nil
}

func (x *Node) GetSleep() *SleepNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Sleep); ok {
			return x.Sleep
		}
	}
	return nil
}

func (x *Node) GetLog() *LogNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *Node) GetBarrier() *BarrierNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Barrier); ok {
			return x.Barrier
		}
	}
	return nil
}

func (x *Node) GetSet() *SetNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *Node) GetDistribute() *DistributeNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Distribute); ok {
			return x.Distribute
		}
	}
	return nil
}

func (x *Node) GetMetric() *MetricNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Metric); ok {
			return x.Metric
		}
	}
	return nil
}

func (x *Node) GetReqMutate() *ReqMutateNode {
	if x != nil {
		if x, ok := x.Type.(*Node_ReqMutate); ok {
			return x.ReqMutate
		}
	}
	return nil
}

func (x *Node) GetResAssert() *ResAssertNode {
	if x != nil {
		if x, ok := x.Type.(*Node_ResAssert); ok {
			return x.ResAssert
		}
	}
	return nil
}

func (x *Node) GetTag() *TagNode {
	if x != nil {
		if x, ok := x.Type.(*Node_Tag); ok {
			return x.Tag
		}
	}
	return nil
}

type isNode_Type interface {
	isNode_Type()
}

type Node_Action struct {
	Action *ActionNode `protobuf:"bytes,2,opt,name=action,proto3,oneof"`
}

type Node_Branch struct {
	Branch *BranchNode `protobuf:"bytes,3,opt,name=branch,proto3,oneof"`
}

type Node_Match struct {
	Match *MatchNode `protobuf:"bytes,4,opt,name=match,proto3,oneof"`
}

type Node_Loop struct {
	Loop *LoopNode `protobuf:"bytes,5,opt,name=loop,proto3,oneof"`
}

type Node_Poll struct {
	Poll *PollNode `protobuf:"bytes,6,opt,name=poll,proto3,oneof"`
}

type Node_Script struct {
	Script *ScriptNode `protobuf:"bytes,7,opt,name=script,proto3,oneof"`
}

type Node_Sleep struct {
	Sleep *SleepNode `protobuf:"bytes,8,opt,name=sleep,proto3,oneof"`
}

type Node_Log struct {
	Log *LogNode `protobuf:"bytes,9,opt,name=log,proto3,oneof"`
}

type Node_Barrier struct {
	Barrier *BarrierNode `protobuf:"bytes,10,opt,name=barrier,proto3,oneof"`
}

type Node_Set struct {
	Set *SetNode `protobuf:"bytes,11,opt,name=set,proto3,oneof"`
}

type Node_Distribute struct {
	Distribute *DistributeNode `protobuf:"bytes,12,opt,name=distribute,proto3,oneof"`
}

type Node_Metric struct {
	Metric *MetricNode `protobuf:"bytes,13,opt,name=metric,proto3,oneof"`
}

type Node_ReqMutate struct {
	ReqMutate *ReqMutateNode `protobuf:"bytes,14,opt,name=req_mutate,json=reqMutate,proto3,oneof"`
}

type Node_ResAssert struct {
	ResAssert *ResAssertNode `protobuf:"bytes,15,opt,name=res_assert,json=resAssert,proto3,oneof"`
}

type Node_Tag struct {
	Tag *TagNode `protobuf:"bytes,16,opt,name=tag,proto3,oneof"`
}

func (*Node_Action) isNode_Type() {}

func (*Node_Branch) isNode_Type() {}

func (*Node_Match) isNode_Type() {}

func (*Node_Loop) isNode_Type() {}

func (*Node_Poll) isNode_Type() {}

func (*Node_Script) isNode_Type() {}

func (*Node_Sleep) isNode_Type() {}

func (*Node_Log) isNode_Type() {}

func (*Node_Barrier) isNode_Type() {}

func (*Node_Set) isNode_Type() {}

func (*Node_Distribute) isNode_Type() {}

func (*Node_Metric) isNode_Type() {}

func (*Node_ReqMutate) isNode_Type() {}

func (*Node_ResAssert) isNode_Type() {}

func (*Node_Tag) isNode_Type() {}

type ActionNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Before        *Pipeline              `protobuf:"bytes,4,opt,name=before,proto3" json:"before,omitempty"`
	After         *Pipeline              `protobuf:"bytes,5,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionNode) Reset() {
	*x = ActionNode{}
	mi := &file_ast_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionNode) ProtoMessage() {}

func (x *ActionNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionNode.ProtoReflect.Descriptor instead.
func (*ActionNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{5}
}

func (x *ActionNode) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ActionNode) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ActionNode) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ActionNode) GetBefore() *Pipeline {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ActionNode) GetAfter() *Pipeline {
	if x != nil {
		return x.After
	}
	return nil
}

type ReqMutateNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqMutateNode) Reset() {
	*x = ReqMutateNode{}
	mi := &file_ast_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqMutateNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMutateNode) ProtoMessage() {}

func (x *ReqMutateNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMutateNode.ProtoReflect.Descriptor instead.
func (*ReqMutateNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{6}
}

func (x *ReqMutateNode) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReqMutateNode) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ResAssertNode struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ExpectCode            int32                  `protobuf:"varint,1,opt,name=expect_code,json=expectCode,proto3" json:"expect_code,omitempty"`
	ExpectPayloadContains string                 `protobuf:"bytes,2,opt,name=expect_payload_contains,json=expectPayloadContains,proto3" json:"expect_payload_contains,omitempty"`
	Extract               map[string]string      `protobuf:"bytes,4,rep,name=extract,proto3" json:"extract,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResAssertNode) Reset() {
	*x = ResAssertNode{}
	mi := &file_ast_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResAssertNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResAssertNode) ProtoMessage() {}

func (x *ResAssertNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResAssertNode.ProtoReflect.Descriptor instead.
func (*ResAssertNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{7}
}

func (x *ResAssertNode) GetExpectCode() int32 {
	if x != nil {
		return x.ExpectCode
	}
	return 0
}

func (x *ResAssertNode) GetExpectPayloadContains() string {
	if x != nil {
		return x.ExpectPayloadContains
	}
	return ""
}

func (x *ResAssertNode) GetExtract() map[string]string {
	if x != nil {
		return x.Extract
	}
	return nil
}

type BranchNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConditionHookId string                 `protobuf:"bytes,1,opt,name=condition_hook_id,json=conditionHookId,proto3" json:"condition_hook_id,omitempty"`
	TruePath        *Pipeline              `protobuf:"bytes,2,opt,name=true_path,json=truePath,proto3" json:"true_path,omitempty"`
	FalsePath       *Pipeline              `protobuf:"bytes,3,opt,name=false_path,json=falsePath,proto3" json:"false_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BranchNode) Reset() {
	*x = BranchNode{}
	mi := &file_ast_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchNode) ProtoMessage() {}

func (x *BranchNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchNode.ProtoReflect.Descriptor instead.
func (*BranchNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{8}
}

func (x *BranchNode) GetConditionHookId() string {
	if x != nil {
		return x.ConditionHookId
	}
	return ""
}

func (x *BranchNode) GetTruePath() *Pipeline {
	if x != nil {
		return x.TruePath
	}
	return nil
}

func (x *BranchNode) GetFalsePath() *Pipeline {
	if x != nil {
		return x.FalsePath
	}
	return nil
}

type MatchNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConditionHookId string                 `protobuf:"bytes,1,opt,name=condition_hook_id,json=conditionHookId,proto3" json:"condition_hook_id,omitempty"`
	Cases           map[string]*Pipeline   `protobuf:"bytes,2,rep,name=cases,proto3" json:"cases,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DefaultPath     *Pipeline              `protobuf:"bytes,3,opt,name=default_path,json=defaultPath,proto3" json:"default_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchNode) Reset() {
	*x = MatchNode{}
	mi := &file_ast_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchNode) ProtoMessage() {}

func (x *MatchNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchNode.ProtoReflect.Descriptor instead.
func (*MatchNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{9}
}

func (x *MatchNode) GetConditionHookId() string {
	if x != nil {
		return x.ConditionHookId
	}
	return ""
}

func (x *MatchNode) GetCases() map[string]*Pipeline {
	if x != nil {
		return x.Cases
	}
	return nil
}

func (x *MatchNode) GetDefaultPath() *Pipeline {
	if x != nil {
		return x.DefaultPath
	}
	return nil
}

type LoopNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Config:
	//
	//	*LoopNode_Count
	//	*LoopNode_Range
	//	*LoopNode_ArrayHookId
	Config        isLoopNode_Config `protobuf_oneof:"config"`
	Logic         *Pipeline         `protobuf:"bytes,4,opt,name=logic,proto3" json:"logic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopNode) Reset() {
	*x = LoopNode{}
	mi := &file_ast_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopNode) ProtoMessage() {}

func (x *LoopNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopNode.ProtoReflect.Descriptor instead.
func (*LoopNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{10}
}

func (x *LoopNode) GetConfig() isLoopNode_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *LoopNode) GetCount() int32 {
	if x != nil {
		if x, ok := x.Config.(*LoopNode_Count); ok {
			return x.Count
		}
	}
	return 0
}

func (x *LoopNode) GetRange() *LoopNode_RangeConfig {
	if x != nil {
		if x, ok := x.Config.(*LoopNode_Range); ok {
			return x.Range
		}
	}
	return nil
}

func (x *LoopNode) GetArrayHookId() string {
	if x != nil {
		if x, ok := x.Config.(*LoopNode_ArrayHookId); ok {
			return x.ArrayHookId
		}
	}
	return ""
}

func (x *LoopNode) GetLogic() *Pipeline {
	if x != nil {
		return x.Logic
	}
	return nil
}

type isLoopNode_Config interface {
	isLoopNode_Config()
}

type LoopNode_Count struct {
	Count int32 `protobuf:"varint,1,opt,name=count,proto3,oneof"`
}

type LoopNode_Range struct {
	Range *LoopNode_RangeConfig `protobuf:"bytes,2,opt,name=range,proto3,oneof"`
}

type LoopNode_ArrayHookId struct {
	ArrayHookId string `protobuf:"bytes,3,opt,name=array_hook_id,json=arrayHookId,proto3,oneof"`
}

func (*LoopNode_Count) isLoopNode_Config() {}

func (*LoopNode_Range) isLoopNode_Config() {}

func (*LoopNode_ArrayHookId) isLoopNode_Config() {}

type PollNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConditionHookId string                 `protobuf:"bytes,1,opt,name=condition_hook_id,json=conditionHookId,proto3" json:"condition_hook_id,omitempty"`
	Logic           *Pipeline              `protobuf:"bytes,2,opt,name=logic,proto3" json:"logic,omitempty"`
	Policy          *PollPolicy            `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PollNode) Reset() {
	*x = PollNode{}
	mi := &file_ast_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollNode) ProtoMessage() {}

func (x *PollNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollNode.ProtoReflect.Descriptor instead.
func (*PollNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{11}
}

func (x *PollNode) GetConditionHookId() string {
	if x != nil {
		return x.ConditionHookId
	}
	return ""
}

func (x *PollNode) GetLogic() *Pipeline {
	if x != nil {
		return x.Logic
	}
	return nil
}

func (x *PollNode) GetPolicy() *PollPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type PollPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      string                 `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,3,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollPolicy) Reset() {
	*x = PollPolicy{}
	mi := &file_ast_schema_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollPolicy) ProtoMessage() {}

func (x *PollPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollPolicy.ProtoReflect.Descriptor instead.
func (*PollPolicy) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{12}
}

func (x *PollPolicy) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *PollPolicy) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *PollPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

type ScriptNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HookId        string                 `protobuf:"bytes,1,opt,name=hook_id,json=hookId,proto3" json:"hook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptNode) Reset() {
	*x = ScriptNode{}
	mi := &file_ast_schema_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptNode) ProtoMessage() {}

func (x *ScriptNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptNode.ProtoReflect.Descriptor instead.
func (*ScriptNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{13}
}

func (x *ScriptNode) GetHookId() string {
	if x != nil {
		return x.HookId
	}
	return ""
}

type SleepNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationS     float64                `protobuf:"fixed64,1,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepNode) Reset() {
	*x = SleepNode{}
	mi := &file_ast_schema_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepNode) ProtoMessage() {}

func (x *SleepNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepNode.ProtoReflect.Descriptor instead.
func (*SleepNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{14}
}

func (x *SleepNode) GetDurationS() float64 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

type LogNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogNode) Reset() {
	*x = LogNode{}
	mi := &file_ast_schema_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogNode) ProtoMessage() {}

func (x *LogNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogNode.ProtoReflect.Descriptor instead.
func (*LogNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{15}
}

func (x *LogNode) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BarrierNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quorum        int32                  `protobuf:"varint,2,opt,name=quorum,proto3" json:"quorum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarrierNode) Reset() {
	*x = BarrierNode{}
	mi := &file_ast_schema_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarrierNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarrierNode) ProtoMessage() {}

func (x *BarrierNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarrierNode.ProtoReflect.Descriptor instead.
func (*BarrierNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{16}
}

func (x *BarrierNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BarrierNode) GetQuorum() int32 {
	if x != nil {
		return x.Quorum
	}
	return 0
}

type SetNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNode) Reset() {
	*x = SetNode{}
	mi := &file_ast_schema_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNode) ProtoMessage() {}

func (x *SetNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNode.ProtoReflect.Descriptor instead.
func (*SetNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{17}
}

func (x *SetNode) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetNode) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *SetNode) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type DistributeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ItemsJson     string                 `protobuf:"bytes,2,opt,name=items_json,json=itemsJson,proto3" json:"items_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistributeNode) Reset() {
	*x = DistributeNode{}
	mi := &file_ast_schema_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistributeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributeNode) ProtoMessage() {}

func (x *DistributeNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributeNode.ProtoReflect.Descriptor instead.
func (*DistributeNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{18}
}

func (x *DistributeNode) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DistributeNode) GetItemsJson() string {
	if x != nil {
		return x.ItemsJson
	}
	return ""
}

type MetricNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricType    string                 `protobuf:"bytes,1,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricNode) Reset() {
	*x = MetricNode{}
	mi := &file_ast_schema_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricNode) ProtoMessage() {}

func (x *MetricNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricNode.ProtoReflect.Descriptor instead.
func (*MetricNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{19}
}

func (x *MetricNode) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *MetricNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TagNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagNode) Reset() {
	*x = TagNode{}
	mi := &file_ast_schema_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagNode) ProtoMessage() {}

func (x *TagNode) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagNode.ProtoReflect.Descriptor instead.
func (*TagNode) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{20}
}

func (x *TagNode) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TagNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LoopNode_RangeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int32                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int32                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopNode_RangeConfig) Reset() {
	*x = LoopNode_RangeConfig{}
	mi := &file_ast_schema_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopNode_RangeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopNode_RangeConfig) ProtoMessage() {}

func (x *LoopNode_RangeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ast_schema_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopNode_RangeConfig.ProtoReflect.Descriptor instead.
func (*LoopNode_RangeConfig) Descriptor() ([]byte, []int) {
	return file_ast_schema_proto_rawDescGZIP(), []int{10, 0}
}

func (x *LoopNode_RangeConfig) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *LoopNode_RangeConfig) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

var File_ast_schema_proto protoreflect.FileDescriptor

const file_ast_schema_proto_rawDesc = "" +
	"\n" +
	"\x10ast_schema.proto\x12\x0ebudment.ast.v1\"\xf4\x01\n" +
	"\bScenario\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x05setup\x18\x02 \x01(\v2\x18.budment.ast.v1.PipelineR\x05setup\x126\n" +
	"\texecution\x18\x03 \x01(\v2\x18.budment.ast.v1.PipelineR\texecution\x126\n" +
	"\x06config\x18\x04 \x01(\v2\x1e.budment.ast.v1.ScenarioConfigR\x06config\x124\n" +
	"\bteardown\x18\x05 \x01(\v2\x18.budment.ast.v1.PipelineR\bteardown\"\xac\x05\n" +
	"\x0eScenarioConfig\x12\x15\n" +
	"\x03vus\x18\x01 \x01(\x05H\x00R\x03vus\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\x02 \x01(\tH\x01R\bduration\x88\x01\x01\x12&\n" +
	"\fmax_duration\x18\x03 \x01(\tH\x02R\vmaxDuration\x88\x01\x01\x12#\n" +
	"\n" +
	"iterations\x18\x04 \x01(\x05H\x03R\n" +
	"iterations\x88\x01\x01\x12\x1e\n" +
	"\bstart_at\x18\x05 \x01(\tH\x04R\astartAt\x88\x01\x01\x12\x19\n" +
	"\x05order\x18\x06 \x01(\x05H\x05R\x05order\x88\x01\x01\x12-\n" +
	"\x06stages\x18\a \x03(\v2\x15.budment.ast.v1.StageR\x06stages\x12N\n" +
	"\n" +
	"thresholds\x18\b \x03(\v2..budment.ast.v1.ScenarioConfig.ThresholdsEntryR\n" +
	"thresholds\x12<\n" +
	"\x04tags\x18\t \x03(\v2(.budment.ast.v1.ScenarioConfig.TagsEntryR\x04tags\x12<\n" +
	"\x18insecure_skip_tls_verify\x18\n" +
	" \x01(\bH\x06R\x15insecureSkipTlsVerify\x88\x01\x01\x1a=\n" +
	"\x0fThresholdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_vusB\v\n" +
	"\t_durationB\x0f\n" +
	"\r_max_durationB\r\n" +
	"\v_iterationsB\v\n" +
	"\t_start_atB\b\n" +
	"\x06_orderB\x1b\n" +
	"\x19_insecure_skip_tls_verify\";\n" +
	"\x05Stage\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\tR\bduration\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x05R\x06target\"6\n" +
	"\bPipeline\x12*\n" +
	"\x05steps\x18\x01 \x03(\v2\x14.budment.ast.v1.NodeR\x05steps\"\xbe\x06\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x06action\x18\x02 \x01(\v2\x1a.budment.ast.v1.ActionNodeH\x00R\x06action\x124\n" +
	"\x06branch\x18\x03 \x01(\v2\x1a.budment.ast.v1.BranchNodeH\x00R\x06branch\x121\n" +
	"\x05match\x18\x04 \x01(\v2\x19.budment.ast.v1.MatchNodeH\x00R\x05match\x12.\n" +
	"\x04loop\x18\x05 \x01(\v2\x18.budment.ast.v1.LoopNodeH\x00R\x04loop\x12.\n" +
	"\x04poll\x18\x06 \x01(\v2\x18.budment.ast.v1.PollNodeH\x00R\x04poll\x124\n" +
	"\x06script\x18\a \x01(\v2\x1a.budment.ast.v1.ScriptNodeH\x00R\x06script\x121\n" +
	"\x05sleep\x18\b \x01(\v2\x19.budment.ast.v1.SleepNodeH\x00R\x05sleep\x12+\n" +
	"\x03log\x18\t \x01(\v2\x17.budment.ast.v1.LogNodeH\x00R\x03log\x127\n" +
	"\abarrier\x18\n" +
	" \x01(\v2\x1b.budment.ast.v1.BarrierNodeH\x00R\abarrier\x12+\n" +
	"\x03set\x18\v \x01(\v2\x17.budment.ast.v1.SetNodeH\x00R\x03set\x12@\n" +
	"\n" +
	"distribute\x18\f \x01(\v2\x1e.budment.ast.v1.DistributeNodeH\x00R\n" +
	"distribute\x124\n" +
	"\x06metric\x18\r \x01(\v2\x1a.budment.ast.v1.MetricNodeH\x00R\x06metric\x12>\n" +
	"\n" +
	"req_mutate\x18\x0e \x01(\v2\x1d.budment.ast.v1.ReqMutateNodeH\x00R\treqMutate\x12>\n" +
	"\n" +
	"res_assert\x18\x0f \x01(\v2\x1d.budment.ast.v1.ResAssertNodeH\x00R\tresAssert\x12+\n" +
	"\x03tag\x18\x10 \x01(\v2\x17.budment.ast.v1.TagNodeH\x00R\x03tagB\x06\n" +
	"\x04type\"\xba\x01\n" +
	"\n" +
	"ActionNode\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x120\n" +
	"\x06before\x18\x04 \x01(\v2\x18.budment.ast.v1.PipelineR\x06before\x12.\n" +
	"\x05after\x18\x05 \x01(\v2\x18.budment.ast.v1.PipelineR\x05after\"\xaf\x01\n" +
	"\rReqMutateNode\x12G\n" +
	"\bmetadata\x18\x01 \x03(\v2+.budment.ast.v1.ReqMutateNode.MetadataEntryR\bmetadata\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xea\x01\n" +
	"\rResAssertNode\x12\x1f\n" +
	"\vexpect_code\x18\x01 \x01(\x05R\n" +
	"expectCode\x126\n" +
	"\x17expect_payload_contains\x18\x02 \x01(\tR\x15expectPayloadContains\x12D\n" +
	"\aextract\x18\x04 \x03(\v2*.budment.ast.v1.ResAssertNode.ExtractEntryR\aextract\x1a:\n" +
	"\fExtractEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x01\n" +
	"\n" +
	"BranchNode\x12*\n" +
	"\x11condition_hook_id\x18\x01 \x01(\tR\x0fconditionHookId\x125\n" +
	"\ttrue_path\x18\x02 \x01(\v2\x18.budment.ast.v1.PipelineR\btruePath\x127\n" +
	"\n" +
	"false_path\x18\x03 \x01(\v2\x18.budment.ast.v1.PipelineR\tfalsePath\"\x84\x02\n" +
	"\tMatchNode\x12*\n" +
	"\x11condition_hook_id\x18\x01 \x01(\tR\x0fconditionHookId\x12:\n" +
	"\x05cases\x18\x02 \x03(\v2$.budment.ast.v1.MatchNode.CasesEntryR\x05cases\x12;\n" +
	"\fdefault_path\x18\x03 \x01(\v2\x18.budment.ast.v1.PipelineR\vdefaultPath\x1aR\n" +
	"\n" +
	"CasesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.budment.ast.v1.PipelineR\x05value:\x028\x01\"\xf3\x01\n" +
	"\bLoopNode\x12\x16\n" +
	"\x05count\x18\x01 \x01(\x05H\x00R\x05count\x12<\n" +
	"\x05range\x18\x02 \x01(\v2$.budment.ast.v1.LoopNode.RangeConfigH\x00R\x05range\x12$\n" +
	"\rarray_hook_id\x18\x03 \x01(\tH\x00R\varrayHookId\x12.\n" +
	"\x05logic\x18\x04 \x01(\v2\x18.budment.ast.v1.PipelineR\x05logic\x1a1\n" +
	"\vRangeConfig\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x05R\x02toB\b\n" +
	"\x06config\"\x9a\x01\n" +
	"\bPollNode\x12*\n" +
	"\x11condition_hook_id\x18\x01 \x01(\tR\x0fconditionHookId\x12.\n" +
	"\x05logic\x18\x02 \x01(\v2\x18.budment.ast.v1.PipelineR\x05logic\x122\n" +
	"\x06policy\x18\x03 \x01(\v2\x1a.budment.ast.v1.PollPolicyR\x06policy\"e\n" +
	"\n" +
	"PollPolicy\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\tR\binterval\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\x12!\n" +
	"\fmax_attempts\x18\x03 \x01(\x05R\vmaxAttempts\"%\n" +
	"\n" +
	"ScriptNode\x12\x17\n" +
	"\ahook_id\x18\x01 \x01(\tR\x06hookId\"*\n" +
	"\tSleepNode\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x01 \x01(\x01R\tdurationS\"#\n" +
	"\aLogNode\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"9\n" +
	"\vBarrierNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06quorum\x18\x02 \x01(\x05R\x06quorum\"P\n" +
	"\aSetNode\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\"A\n" +
	"\x0eDistributeNode\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"items_json\x18\x02 \x01(\tR\titemsJson\"W\n" +
	"\n" +
	"MetricNode\x12\x1f\n" +
	"\vmetric_type\x18\x01 \x01(\tR\n" +
	"metricType\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"1\n" +
	"\aTagNode\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB,Z*github.com/budment/budment/core/pkg/pb/astb\x06proto3"

var (
	file_ast_schema_proto_rawDescOnce sync.Once
	file_ast_schema_proto_rawDescData []byte
)

func file_ast_schema_proto_rawDescGZIP() []byte {
	file_ast_schema_proto_rawDescOnce.Do(func() {
		file_ast_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ast_schema_proto_rawDesc), len(file_ast_schema_proto_rawDesc)))
	})
	return file_ast_schema_proto_rawDescData
}

var file_ast_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_ast_schema_proto_goTypes = []any{
	(*Scenario)(nil),             // 0: budment.ast.v1.Scenario
	(*ScenarioConfig)(nil),       // 1: budment.ast.v1.ScenarioConfig
	(*Stage)(nil),                // 2: budment.ast.v1.Stage
	(*Pipeline)(nil),             // 3: budment.ast.v1.Pipeline
	(*Node)(nil),                 // 4: budment.ast.v1.Node
	(*ActionNode)(nil),           // 5: budment.ast.v1.ActionNode
	(*ReqMutateNode)(nil),        // 6: budment.ast.v1.ReqMutateNode
	(*ResAssertNode)(nil),        // 7: budment.ast.v1.ResAssertNode
	(*BranchNode)(nil),           // 8: budment.ast.v1.BranchNode
	(*MatchNode)(nil),            // 9: budment.ast.v1.MatchNode
	(*LoopNode)(nil),             // 10: budment.ast.v1.LoopNode
	(*PollNode)(nil),             // 11: budment.ast.v1.PollNode
	(*PollPolicy)(nil),           // 12: budment.ast.v1.PollPolicy
	(*ScriptNode)(nil),           // 13: budment.ast.v1.ScriptNode
	(*SleepNode)(nil),            // 14: budment.ast.v1.SleepNode
	(*LogNode)(nil),              // 15: budment.ast.v1.LogNode
	(*BarrierNode)(nil),          // 16: budment.ast.v1.BarrierNode
	(*SetNode)(nil),              // 17: budment.ast.v1.SetNode
	(*DistributeNode)(nil),       // 18: budment.ast.v1.DistributeNode
	(*MetricNode)(nil),           // 19: budment.ast.v1.MetricNode
	(*TagNode)(nil),              // 20: budment.ast.v1.TagNode
	nil,                          // 21: budment.ast.v1.ScenarioConfig.ThresholdsEntry
	nil,                          // 22: budment.ast.v1.ScenarioConfig.TagsEntry
	nil,                          // 23: budment.ast.v1.ReqMutateNode.MetadataEntry
	nil,                          // 24: budment.ast.v1.ResAssertNode.ExtractEntry
	nil,                          // 25: budment.ast.v1.MatchNode.CasesEntry
	(*LoopNode_RangeConfig)(nil), // 26: budment.ast.v1.LoopNode.RangeConfig
}
var file_ast_schema_proto_depIdxs = []int32{
	3,  // 0: budment.ast.v1.Scenario.setup:type_name -> budment.ast.v1.Pipeline
	3,  // 1: budment.ast.v1.Scenario.execution:type_name -> budment.ast.v1.Pipeline
	1,  // 2: budment.ast.v1.Scenario.config:type_name -> budment.ast.v1.ScenarioConfig
	3,  // 3: budment.ast.v1.Scenario.teardown:type_name -> budment.ast.v1.Pipeline
	2,  // 4: budment.ast.v1.ScenarioConfig.stages:type_name -> budment.ast.v1.Stage
	21, // 5: budment.ast.v1.ScenarioConfig.thresholds:type_name -> budment.ast.v1.ScenarioConfig.ThresholdsEntry
	22, // 6: budment.ast.v1.ScenarioConfig.tags:type_name -> budment.ast.v1.ScenarioConfig.TagsEntry
	4,  // 7: budment.ast.v1.Pipeline.steps:type_name -> budment.ast.v1.Node
	5,  // 8: budment.ast.v1.Node.action:type_name -> budment.ast.v1.ActionNode
	8,  // 9: budment.ast.v1.Node.branch:type_name -> budment.ast.v1.BranchNode
	9,  // 10: budment.ast.v1.Node.match:type_name -> budment.ast.v1.MatchNode
	10, // 11: budment.ast.v1.Node.loop:type_name -> budment.ast.v1.LoopNode
	11, // 12: budment.ast.v1.Node.poll:type_name -> budment.ast.v1.PollNode
	13, // 13: budment.ast.v1.Node.script:type_name -> budment.ast.v1.ScriptNode
	14, // 14: budment.ast.v1.Node.sleep:type_name -> budment.ast.v1.SleepNode
	15, // 15: budment.ast.v1.Node.log:type_name -> budment.ast.v1.LogNode
	16, // 16: budment.ast.v1.Node.barrier:type_name -> budment.ast.v1.BarrierNode
	17, // 17: budment.ast.v1.Node.set:type_name -> budment.ast.v1.SetNode
	18, // 18: budment.ast.v1.Node.distribute:type_name -> budment.ast.v1.DistributeNode
	19, // 19: budment.ast.v1.Node.metric:type_name -> budment.ast.v1.MetricNode
	6,  // 20: budment.ast.v1.Node.req_mutate:type_name -> budment.ast.v1.ReqMutateNode
	7,  // 21: budment.ast.v1.Node.res_assert:type_name -> budment.ast.v1.ResAssertNode
	20, // 22: budment.ast.v1.Node.tag:type_name -> budment.ast.v1.TagNode
	3,  // 23: budment.ast.v1.ActionNode.before:type_name -> budment.ast.v1.Pipeline
	3,  // 24: budment.ast.v1.ActionNode.after:type_name -> budment.ast.v1.Pipeline
	23, // 25: budment.ast.v1.ReqMutateNode.metadata:type_name -> budment.ast.v1.ReqMutateNode.MetadataEntry
	24, // 26: budment.ast.v1.ResAssertNode.extract:type_name -> budment.ast.v1.ResAssertNode.ExtractEntry
	3,  // 27: budment.ast.v1.BranchNode.true_path:type_name -> budment.ast.v1.Pipeline
	3,  // 28: budment.ast.v1.BranchNode.false_path:type_name -> budment.ast.v1.Pipeline
	25, // 29: budment.ast.v1.MatchNode.cases:type_name -> budment.ast.v1.MatchNode.CasesEntry
	3,  // 30: budment.ast.v1.MatchNode.default_path:type_name -> budment.ast.v1.Pipeline
	26, // 31: budment.ast.v1.LoopNode.range:type_name -> budment.ast.v1.LoopNode.RangeConfig
	3,  // 32: budment.ast.v1.LoopNode.logic:type_name -> budment.ast.v1.Pipeline
	3,  // 33: budment.ast.v1.PollNode.logic:type_name -> budment.ast.v1.Pipeline
	12, // 34: budment.ast.v1.PollNode.policy:type_name -> budment.ast.v1.PollPolicy
	3,  // 35: budment.ast.v1.MatchNode.CasesEntry.value:type_name -> budment.ast.v1.Pipeline
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_ast_schema_proto_init() }
func file_ast_schema_proto_init() {
	if File_ast_schema_proto != nil {
		return
	}
	file_ast_schema_proto_msgTypes[1].OneofWrappers = []any{}
	file_ast_schema_proto_msgTypes[4].OneofWrappers = []any{
		(*Node_Action)(nil),
		(*Node_Branch)(nil),
		(*Node_Match)(nil),
		(*Node_Loop)(nil),
		(*Node_Poll)(nil),
		(*Node_Script)(nil),
		(*Node_Sleep)(nil),
		(*Node_Log)(nil),
		(*Node_Barrier)(nil),
		(*Node_Set)(nil),
		(*Node_Distribute)(nil),
		(*Node_Metric)(nil),
		(*Node_ReqMutate)(nil),
		(*Node_ResAssert)(nil),
		(*Node_Tag)(nil),
	}
	file_ast_schema_proto_msgTypes[10].OneofWrappers = []any{
		(*LoopNode_Count)(nil),
		(*LoopNode_Range)(nil),
		(*LoopNode_ArrayHookId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ast_schema_proto_rawDesc), len(file_ast_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ast_schema_proto_goTypes,
		DependencyIndexes: file_ast_schema_proto_depIdxs,
		MessageInfos:      file_ast_schema_proto_msgTypes,
	}.Build()
	File_ast_schema_proto = out.File
	file_ast_schema_proto_goTypes = nil
	file_ast_schema_proto_depIdxs = nil
}
