// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: ast_schema.proto

/* eslint-disable */

export const protobufPackage = "blaster.ast.v1";

export interface Scenario {
  name: string;
  setup: Pipeline | undefined;
  execution: Pipeline | undefined;
  config: ScenarioConfig | undefined;
}

export interface ScenarioConfig {
  /** Number of concurrent virtual users. Defaults to 1. */
  vus?:
    | number
    | undefined;
  /** Scenario run duration. Stops when reached. */
  duration: string;
  /** Hard upper limit for the entire scenario. */
  maxDuration: string;
  /** Number of iterations to execute. Defaults to 1. */
  iterations?:
    | number
    | undefined;
  /** Exact time to start the scenario. Takes precedence over order. */
  startAt: string;
  /** Execution order. Scenarios with the same order start together. */
  order?:
    | number
    | undefined;
  /** Optional load stages for gradually changing VUs. */
  stages: Stage[];
  /** Pass/fail conditions for scenario metrics. */
  thresholds: { [key: string]: string };
  /** Custom metadata attached to the scenario. */
  tags: { [key: string]: string };
  /** Disable TLS certificate verification. */
  insecureSkipTlsVerify?: boolean | undefined;
  autoPlumb?: boolean | undefined;
}

export interface ScenarioConfig_ThresholdsEntry {
  key: string;
  value: string;
}

export interface ScenarioConfig_TagsEntry {
  key: string;
  value: string;
}

export interface Stage {
  /** Duration of this stage. */
  duration: string;
  /** Target number of virtual users. */
  target: number;
}

export interface Pipeline {
  steps: Node[];
}

export interface Node {
  id: string;
  http?: HttpNode | undefined;
  branch?: BranchNode | undefined;
  match?: MatchNode | undefined;
  loop?: LoopNode | undefined;
  poll?: PollNode | undefined;
  script?: ScriptNode | undefined;
}

export interface HttpNode {
  method: string;
  url: string;
  beforeHookId: string;
  afterHookId: string;
}

export interface BranchNode {
  conditionHookId: string;
  truePath: Pipeline | undefined;
  falsePath: Pipeline | undefined;
}

export interface MatchNode {
  conditionHookId: string;
  cases: { [key: string]: Pipeline };
  defaultPath: Pipeline | undefined;
}

export interface MatchNode_CasesEntry {
  key: string;
  value: Pipeline | undefined;
}

export interface LoopNode {
  count?: number | undefined;
  range?: LoopNode_RangeConfig | undefined;
  arrayHookId?: string | undefined;
  logic: Pipeline | undefined;
}

export interface LoopNode_RangeConfig {
  from: number;
  to: number;
}

export interface PollNode {
  conditionHookId: string;
  logic: Pipeline | undefined;
  policy: PollPolicy | undefined;
}

export interface PollPolicy {
  interval: string;
  timeout: string;
  maxAttempts: number;
}

export interface ScriptNode {
  hookId: string;
}
