// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: ast_schema.proto

/* eslint-disable */

export const protobufPackage = "blaster.ast.v1";

export interface Scenario {
  name: string;
  setup: Pipeline | undefined;
  execution: Pipeline | undefined;
  config: ScenarioConfig | undefined;
}

export interface ScenarioConfig {
  vus: number;
  duration: string;
  maxDuration: string;
  order: number;
}

export interface Pipeline {
  steps: Node[];
}

export interface Node {
  id: string;
  http?: HttpNode | undefined;
  branch?: BranchNode | undefined;
  match?: MatchNode | undefined;
  loop?: LoopNode | undefined;
  poll?: PollNode | undefined;
  script?: ScriptNode | undefined;
}

export interface HttpNode {
  method: string;
  url: string;
  beforeHookId: string;
  afterHookId: string;
}

export interface BranchNode {
  conditionHookId: string;
  truePath: Pipeline | undefined;
  falsePath: Pipeline | undefined;
}

export interface MatchNode {
  conditionHookId: string;
  cases: { [key: string]: Pipeline };
  defaultPath: Pipeline | undefined;
}

export interface MatchNode_CasesEntry {
  key: string;
  value: Pipeline | undefined;
}

export interface LoopNode {
  count?: number | undefined;
  range?: LoopNode_RangeConfig | undefined;
  arrayHookId?: string | undefined;
  logic: Pipeline | undefined;
}

export interface LoopNode_RangeConfig {
  from: number;
  to: number;
}

export interface PollNode {
  conditionHookId: string;
  logic: Pipeline | undefined;
  policy: PollPolicy | undefined;
}

export interface PollPolicy {
  interval: string;
  timeout: string;
  maxAttempts: number;
}

export interface ScriptNode {
  hookId: string;
}
