// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: ast_schema.proto

/* eslint-disable */

export const protobufPackage = "blaster.ast.v1";

export interface Scenario {
  name?: string | undefined;
  setup?: Pipeline | undefined;
  execution?: Pipeline | undefined;
  config?: ScenarioConfig | undefined;
}

export interface ScenarioConfig {
  /** Number of concurrent virtual users. Defaults to 1. */
  vus?:
    | number
    | undefined;
  /** Scenario run duration. Stops when reached. */
  duration?:
    | string
    | undefined;
  /** Hard upper limit for the entire scenario. */
  maxDuration?:
    | string
    | undefined;
  /** Number of iterations to execute. Defaults to 1. */
  iterations?:
    | number
    | undefined;
  /** Exact time to start the scenario. Takes precedence over order. */
  startAt?:
    | string
    | undefined;
  /** Execution order. Scenarios with the same order start together. */
  order?:
    | number
    | undefined;
  /** Optional load stages for gradually changing VUs. */
  stages?:
    | Stage[]
    | undefined;
  /** Pass/fail conditions for scenario metrics. */
  thresholds?:
    | { [key: string]: string }
    | undefined;
  /** Custom metadata attached to the scenario. */
  tags?:
    | { [key: string]: string }
    | undefined;
  /** Disable TLS certificate verification. */
  insecureSkipTlsVerify?: boolean | undefined;
}

export interface ScenarioConfig_ThresholdsEntry {
  key: string;
  value: string;
}

export interface ScenarioConfig_TagsEntry {
  key: string;
  value: string;
}

export interface Stage {
  /** Duration of this stage. */
  duration?:
    | string
    | undefined;
  /** Target number of virtual users. */
  target?: number | undefined;
}

export interface Pipeline {
  steps?: Node[] | undefined;
}

export interface Node {
  id?: string | undefined;
  action?: ActionNode | undefined;
  branch?: BranchNode | undefined;
  match?: MatchNode | undefined;
  loop?: LoopNode | undefined;
  poll?: PollNode | undefined;
  script?: ScriptNode | undefined;
  sleep?: SleepNode | undefined;
  log?: LogNode | undefined;
  barrier?: BarrierNode | undefined;
  set?: SetNode | undefined;
  distribute?: DistributeNode | undefined;
  metric?: MetricNode | undefined;
  reqMutate?: ReqMutateNode | undefined;
  resAssert?: ResAssertNode | undefined;
}

export interface ActionNode {
  protocol?: string | undefined;
  method?: string | undefined;
  target?: string | undefined;
  before?: Pipeline | undefined;
  after?: Pipeline | undefined;
}

export interface ReqMutateNode {
  metadata?: { [key: string]: string } | undefined;
  payload?: string | undefined;
}

export interface ReqMutateNode_MetadataEntry {
  key: string;
  value: string;
}

export interface ResAssertNode {
  expectCode?: number | undefined;
  expectPayloadContains?: string | undefined;
  extract?: { [key: string]: string } | undefined;
}

export interface ResAssertNode_ExtractEntry {
  key: string;
  value: string;
}

export interface BranchNode {
  conditionHookId?: string | undefined;
  truePath?: Pipeline | undefined;
  falsePath?: Pipeline | undefined;
}

export interface MatchNode {
  conditionHookId?: string | undefined;
  cases?: { [key: string]: Pipeline } | undefined;
  defaultPath?: Pipeline | undefined;
}

export interface MatchNode_CasesEntry {
  key: string;
  value?: Pipeline | undefined;
}

export interface LoopNode {
  count?: number | undefined;
  range?: LoopNode_RangeConfig | undefined;
  arrayHookId?: string | undefined;
  logic?: Pipeline | undefined;
}

export interface LoopNode_RangeConfig {
  from?: number | undefined;
  to?: number | undefined;
}

export interface PollNode {
  conditionHookId?: string | undefined;
  logic?: Pipeline | undefined;
  policy?: PollPolicy | undefined;
}

export interface PollPolicy {
  interval?: string | undefined;
  timeout?: string | undefined;
  maxAttempts?: number | undefined;
}

export interface ScriptNode {
  hookId?: string | undefined;
}

export interface SleepNode {
  durationS?: number | undefined;
}

export interface LogNode {
  message?: string | undefined;
}

export interface BarrierNode {
  name?: string | undefined;
  quorum?: number | undefined;
}

export interface SetNode {
  key?: string | undefined;
  valueJson?: string | undefined;
  scope?: string | undefined;
}

export interface DistributeNode {
  key?: string | undefined;
  itemsJson?: string | undefined;
}

export interface MetricNode {
  metricType?: string | undefined;
  name?: string | undefined;
  value?: string | undefined;
}
